"""Shared dashboard typography, responsive layout, and market-alignment styling."""
def load_css():
 return """
<style>
:root{--dash-font:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.stApp{background:#0E1117}.block-container{padding-top:.65rem;padding-bottom:1.2rem;max-width:98%}
.stApp h1,.stApp h2,.stApp h3,.stApp h4{font-family:var(--dash-font)!important;color:#F4F7FB!important;font-weight:750!important;letter-spacing:-.015em!important}
.stApp h1{font-size:1.8rem!important;line-height:1.15!important;margin:.15rem 0 .45rem!important}.stApp h2{font-size:1.3rem!important;line-height:1.2!important;margin:.8rem 0 .4rem!important}.stApp h3{font-size:1.08rem!important;line-height:1.25!important;margin:.65rem 0 .3rem!important}
.stApp p,.stApp li,.stApp .stMarkdown,[data-testid="stMarkdownContainer"]{font-family:var(--dash-font)!important;font-size:.94rem!important;line-height:1.5!important;color:#D8E1ED!important}.stApp .stCaption{font-family:var(--dash-font)!important;color:#9FB0C7!important;font-size:.82rem!important;line-height:1.35!important}
.metric-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;width:100%;margin:0 0 12px}.metric-card{background:linear-gradient(145deg,#152238,#101827);border:1px solid #30425F;border-radius:12px;padding:11px;min-height:70px;box-sizing:border-box;min-width:0;box-shadow:0 3px 12px rgba(0,0,0,.18)}.metric-card small{display:block;color:#AFC0D6!important;font-size:.72rem!important;line-height:1.2!important;font-weight:650!important;letter-spacing:.035em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.metric-card b{display:block;color:#FFFFFF!important;font-size:1.02rem!important;line-height:1.25!important;font-weight:800!important;margin-top:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.s1-analysis-row{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:4px!important;background:linear-gradient(145deg,#152238,#111A29);border:1px solid #30425F;border-radius:11px;padding:12px 14px!important;margin:8px 0!important;min-height:0!important;box-sizing:border-box!important}.s1-label{display:block!important;width:100%!important;font-family:var(--dash-font)!important;font-size:.74rem!important;line-height:1.2!important;font-weight:750!important;color:#9FB4CF!important;letter-spacing:.06em!important;text-transform:uppercase!important}.s1-value{display:block!important;width:100%!important;font-family:var(--dash-font)!important;font-size:1.02rem!important;line-height:1.35!important;font-weight:800!important;color:#FFFFFF!important;white-space:normal!important}.s1-detail{display:block!important;width:100%!important;font-family:var(--dash-font)!important;font-size:.82rem!important;line-height:1.4!important;color:#B9C8DA!important;white-space:normal!important}
.stExpander{border:1px solid #30425F!important;border-radius:11px!important;background:#111B2D!important;margin:8px 0!important}.stExpander summary{font-size:1rem!important;font-weight:750!important;color:#F4F7FB!important;padding:4px 2px}.stExpander summary p{font-size:1rem!important;font-weight:750!important;color:#F4F7FB!important}
.stDataFrame{border-radius:10px;max-width:100%}[data-testid="stDataFrame"]{max-width:100%;overflow:hidden}.stDataFrame div[role="grid"]{font-size:.84rem}
.stButton>button,.stDownloadButton>button{font-family:var(--dash-font)!important;font-size:.86rem!important;font-weight:700!important;min-height:42px!important;border-radius:10px!important}
.stTabs [data-baseweb="tab-list"]{gap:6px;overflow-x:auto;padding:3px 2px 7px}.stTabs [data-baseweb="tab"]{height:40px;padding:0 14px;border:1px solid #30425F;border-radius:9px;background:#111B2D;color:#B9C6D8;font-size:.82rem;font-weight:700;white-space:nowrap}.stTabs [aria-selected="true"]{background:#1b2d49!important;color:#FFFFFF!important;border-color:#4a6692!important}
.alignment-panel{background:#111B2D;border:1px solid #30425F;border-radius:12px;padding:13px;margin:9px 0 14px}.alignment-head strong{font-size:1.05rem;color:#FFF}.alignment-head span{font-size:.76rem;color:#AFC0D6}.alignment-head>b{font-size:.85rem;color:#FFF}.alignment-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.alignment-item{border:1px solid #30425F;border-radius:9px;padding:10px}.alignment-item small{font-size:.70rem;color:#AFC0D6}.alignment-item strong{font-size:.92rem;color:#FFF}.alignment-item span{font-size:.72rem;color:#AFC0D6}.alignment-foot{font-size:.70rem;color:#8FA0B5;margin-top:9px}
footer,header{visibility:hidden}
@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.alignment-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:600px){.block-container{padding-left:.65rem;padding-right:.65rem}.stApp h1{font-size:1.5rem!important}.stApp h2{font-size:1.15rem!important}.stApp h3{font-size:1rem!important}.stApp p,.stApp li,.stApp .stMarkdown,[data-testid="stMarkdownContainer"]{font-size:.88rem!important}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.metric-card{min-height:64px;padding:9px}.metric-card small{font-size:.66rem!important}.metric-card b{font-size:.9rem!important}.s1-analysis-row{padding:11px 12px!important;margin:7px 0!important}.s1-label{font-size:.70rem!important}.s1-value{font-size:.92rem!important}.s1-detail{font-size:.77rem!important;line-height:1.4!important}.alignment-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.alignment-item{padding:8px}.alignment-item strong{font-size:.82rem}.stExpander summary,.stExpander summary p{font-size:.9rem!important}}
</style>
"""