"""Configuration for the NIFTY 500 PDH/PDL open-reversal paper strategy."""

import os
import time

os.environ["TZ"] = "Asia/Kolkata"
if hasattr(time, "tzset"):
    time.tzset()

STOCK_UNIVERSE = "NIFTY_500"
MAX_STOCKS = 500
MARKET_OPEN = "09:15"
OBSERVATION_START = "09:15"
PREMARKET_PREP_TIME = "09:20"
TRADING_START = "09:45"
LAST_ENTRY_TIME = "14:00"
SQUARE_OFF_TIME = "15:00"
MARKET_CLOSE = "15:30"

REQUIRE_MARKET_ALIGNMENT = True
REQUIRE_STOCK_ALIGNMENT = True
ENABLE_LONG = True
ENABLE_SHORT = True

STRATEGY_NAME = "NIFTY_500_PDH_PDL_OPEN_REVERSAL"
ENTRY_TIMEFRAME = "1m"
ENTRY_CONFIRMATION_TIMEFRAME = "1m"
STOP_LOSS_METHOD = "TODAY_LOW_HIGH_AT_TRIGGER"
RISK_REWARD_RATIO = 1.25
MIN_RR_RATIO = 1.25
MAX_TRIGGER_AGE_MINUTES = 2

TOTAL_CAPITAL = 250000
MAX_RISK_PER_TRADE = 1500
MIN_REQUIRED_RISK = 1400
MAX_TRADES_PER_STOCK = 1
MAX_OPEN_POSITIONS = 2
DAILY_MAX_LOSS = 3750
DAILY_PROFIT_TARGET = 5000
COOLDOWN_MINUTES = 15
POSITION_SIZE_METHOD = "RISK_AND_CAPITAL"
PAPER_TRADING = True
LIVE_TRADING = False
SCAN_INTERVAL_SECONDS = 60

# High-liquidity universe: top 25% by previous-day turnover.
# Kept configurable so the threshold can be changed without editing scanner logic.
HIGH_LIQUIDITY_PERCENTILE = 0.75

TRADE_LOG_FILE = "outputs/trades.csv"
SIGNAL_LOG_FILE = "outputs/signals.csv"
GAP_ANALYSIS_FILE = "outputs/gap_analysis.csv"
