"""
NIFTY LARGEMIDCAP 250 PULLBACK BREAKOUT TRADING BOT
===================================================
"""

STOCK_UNIVERSE = "NIFTY_LARGEMIDCAP_250"
MAX_STOCKS = 250

MARKET_OPEN = "09:15"
OBSERVATION_START = "09:15"
TRADING_START = "09:45"
LAST_ENTRY_TIME = "14:00"
SQUARE_OFF_TIME = "15:00"
MARKET_CLOSE = "15:30"

REQUIRE_BREAKOUT_AFTER_TRADING_START = True
ALLOW_NEW_ENTRIES_AFTER_LAST_ENTRY = False
MANDATORY_SQUARE_OFF = True

SETUP_TIMEFRAME = "5m"
PULLBACK_TIMEFRAME = "5m"
ENTRY_TIMEFRAME = "1m"
ENTRY_CONFIRMATION_TIMEFRAME = "1m"

ENABLE_LONG = True
ENABLE_SHORT = True

REQUIRE_MARKET_ALIGNMENT = True
REQUIRE_SECTOR_ALIGNMENT = True
REQUIRE_STOCK_ALIGNMENT = True

FREEZE_BREAKOUT_LEVEL = True
REQUIRE_CANDLE_CLOSE_CONFIRMATION = True

MIN_PULLBACK_CANDLES = 2
ENTRY_METHOD = "ONE_MINUTE_CLOSE"
ENTRY_AT_CONFIRMATION_CLOSE = True
STOP_LOSS_METHOD = "PULLBACK_EXTREME"
RISK_REWARD_RATIO = 1.0

TOTAL_CAPITAL = 250000
MAX_RISK_PER_TRADE = 1250
MIN_REQUIRED_RISK = 1240
RISK_PERCENT = 0.5

MAX_TRADES_PER_STOCK = 1
MAX_OPEN_POSITIONS = 2

DAILY_MAX_LOSS = 3750
DAILY_PROFIT_TARGET = 5000
COOLDOWN_MINUTES = 15

POSITION_SIZE_METHOD = "RISK_AND_CAPITAL"

PAPER_TRADING = True
LIVE_TRADING = False

# A complete 250-stock scan is network-heavy. Thirty seconds is fast enough
# for a 1-minute confirmation strategy while giving the data provider and
# scanner time to finish cleanly.
SCAN_INTERVAL_SECONDS = 30

TRADE_LOG_FILE = "outputs/trades.csv"
SIGNAL_LOG_FILE = "outputs/signals.csv"
