"""Configuration for the NIFTY 500 paper strategies."""
import os
import time

os.environ["TZ"] = "Asia/Kolkata"
if hasattr(time, "tzset"):
    time.tzset()

STOCK_UNIVERSE = "NIFTY_500"
MAX_STOCKS = 500
MARKET_OPEN = "09:15"
OBSERVATION_START = "09:15"
PREMARKET_PREP_TIME = "09:20"
TRADING_START = "09:45"
LAST_ENTRY_TIME = "14:00"
SQUARE_OFF_TIME = "15:00"
MARKET_CLOSE = "15:30"
REQUIRE_MARKET_ALIGNMENT = True
REQUIRE_STOCK_ALIGNMENT = False
NIFTY500_MIN_CHANGE_PCT = 0.0
ENABLE_LONG = True
ENABLE_SHORT = True
STRATEGY_NAME = "NIFTY_500_PDH_PDL_OPEN_RETURN"
STRATEGY2_NAME = "GAP_EXTENSION_REVERSAL_BUY_SELL"
ENTRY_TIMEFRAME = "LIVE_LTP"
ENTRY_CONFIRMATION_TIMEFRAME = "LIVE_LTP_NO_CANDLE_CLOSE"
STOP_LOSS_METHOD = "BUY_TODAY_LOW_SELL_TODAY_HIGH"
STRATEGY2_STOP_LOSS_METHOD = "SELL_TODAY_HIGH_BUY_TODAY_LOW"
STRATEGY2_TARGET_METHOD = "SELL_PDH_BUY_PDL"
RISK_REWARD_RATIO = 1.25
MIN_RR_RATIO = 1.25
MAX_TRIGGER_AGE_MINUTES = 2
TOTAL_CAPITAL = 250000
STRATEGY2_TOTAL_CAPITAL = 250000
MAX_RISK_PER_TRADE = 1500
MIN_REQUIRED_RISK = 1400
MAX_TRADES_PER_STOCK = 1
MAX_OPEN_POSITIONS = 2
STRATEGY2_MAX_OPEN_POSITIONS = 2
DAILY_MAX_LOSS = 3000
DAILY_PROFIT_TARGET = 5000
STRATEGY2_DAILY_MAX_LOSS = 3000
STRATEGY2_DAILY_PROFIT_TARGET = 5000
COOLDOWN_MINUTES = 15
POSITION_SIZE_METHOD = "RISK_AND_CAPITAL"
PAPER_TRADING = True
LIVE_TRADING = False
SCAN_INTERVAL_SECONDS = 5
MARKET_DATA_REFRESH_SECONDS = 5
BETA_LOOKBACK_DAYS = 60
TRADE_LOG_FILE = "outputs/trades.csv"
SIGNAL_LOG_FILE = "outputs/signals.csv"
GAP_ANALYSIS_FILE = "outputs/gap_analysis.csv"
STRATEGY2_TRADE_LOG_FILE = "outputs/strategy2_trades.csv"
STRATEGY2_SIGNAL_LOG_FILE = "outputs/strategy2_signals.csv"
