[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#000000"
secondaryBackgroundColor = "#000000"
textColor = "#F5F7FB"
font = "sans serif"
